#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp
verilator -Wall --cc --trace f1_fsm.sv
verilator -Wall --cc --trace clktick.sv
verilator -Wall --cc --trace delay.sv
verilator -Wall --cc --trace mux.sv
verilator -Wall --cc --trace lfsr.sv

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop
make -j -C obj_dir/ -f Vf1_fsm.mk Vf1_fsm
make -j -C obj_dir/ -f Vclktick.mk Vclktick
make -j -C obj_dir/ -f Vdelay.mk Vdelay
make -j -C obj_dir/ -f Vmux.mk Vmux
make -j -C obj_dir/ -f Vlfsr.mk Vlfsr

# run executable simulation file
obj_dir/Vtop