#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop
make -j -C obj_dir/ -f VregFile.mk VregFile
make -j -C obj_dir/ -f Valu.mk Valu
make -j -C obj_dir/ -f Vmux2.mk Vmux2

# run executable simulation file
obj_dir/Vtop