#?/bin/sh

# cleanup
rm -rf obj_dir
rm -f PCReg.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace PCReg.sv --exe PCReg_tb.cpp
verilator -Wall --cc --trace ProgramCounter.sv --exe PCReg_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPCReg.mk VPCReg

#run executable simulation file
obj_dir/VPCReg

# source ./doit.sh to run this
